### ISSUE TITLE
patched

### ISSUE THREAD

**Issue by Vamp999** [YABOIpy/GoGen#4]

**Comment by YABOIpy** [comment]
Could u show me what the error is

**Comment by Vamp999** [comment]
> Could u show me what the error is

keeps saying ratelimit

**Comment by Vamp999** [comment]
![image](https://user-images.githubusercontent.com/98104219/208291790-714bcda4-ea9e-4427-8177-41fc2a17751b.png)

**Comment by YABOIpy** [comment]
Its not patched its a http client error ive put this in the description why i didnt fix this error

**Comment by Vamp999** [comment]
> Its not patched its a http client error ive put this in the description why i didnt fix this error

oh ye
